#! /usr/bin/python


from __future__ import unicode_literals
import youtube_dl
import sys

from bs4 import BeautifulSoup
import requests
import os


ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
}

def set_in_order(linkliste):
    soup = BeautifulSoup(requests.get(
        linkliste).text, "lxml") 
    pesme = []
    folder = os.listdir()

    for link in soup.find_all('a'):
        url = link.get('href')
        if url.startswith('/watch'):
            if not(url in pesme):
                pesme.append(url)

    red = 1
    for link in pesme[1:]:
        lst = link.find('&list')
        link = link[:lst]
        r = requests.get('https://www.youtube.com/' + link)
        ime = BeautifulSoup(r.text, "lxml").title.text[:-10]
        for mp3 in folder:
            if mp3.startswith(ime):
                mp3mod = str(red) + '.' + mp3
                os.rename(mp3, mp3mod)
                print(mp3)
                print(mp3mod)
                print('-------------')
                
        red+=1

def skini_plejlistu(plejlista):
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([plejlista])


if __name__ == '__main__':
    if len(sys.argv) == 2:
        url = sys.argv[1]
    else:
        url = input('Daj link plejliste: ')
    skini_plejlistu(url)
    set_in_order(url)
