#! /usr/bin/python

from __future__ import unicode_literals
import youtube_dl
import sys


ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
}
def skini_plejlistu(plejlista):
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download([plejlista])

if __name__ == '__main__':
    if len(sys.argv) == 2:
        url = sys.argv[1]
    else:
        url = input('Daj link plejliste: ')
    skini_plejlistu(url)
